services:
  mongo_db:
    container_name: igclone2_db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis:7

  server:
    build: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo_db
      - redis
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_MODE=development
      - VITE_SERVER_PORT=4000
      - VITE_BASE_URI=https://zsrh6d-4000.csb.app/api
      - VITE_BASE_SOCKET_URI=https://zsrh6d-4000.csb.app
    depends_on:
      - server

volumes:
  mongo_db: {}
